package dialect

import (
	"strconv"
	"strings"
)

type Dialect string

const (
	SQLite     Dialect = "sqlite"
	MySQL      Dialect = "mysql"
	PostgreSQL Dialect = "pgsql"
)

func (d Dialect) String() string { return string(d) }

// Placeholder 返回第 i 个占位符（从 1 开始）。
// SQLite/MySQL 使用 ?；PostgreSQL 使用 $1, $2, ...
func (d Dialect) Placeholder(i int) string {
	if d == PostgreSQL {
		return "$" + strconv.Itoa(i)
	}
	return "?"
}

// RewritePlaceholders 将 SQL 中的 ? 替换为当前数据库的占位符。
func (d Dialect) RewritePlaceholders(sql string) string {
	if d == PostgreSQL {
		var b strings.Builder
		n := 0
		for _, r := range sql {
			if r == '?' {
				n++
				b.WriteString("$")
				b.WriteString(strconv.Itoa(n))
			} else {
				b.WriteRune(r)
			}
		}
		return b.String()
	}
	return sql
}

// NowLiteral 返回当前时间字面量。
func (d Dialect) NowLiteral() string {
	switch d {
	case SQLite:
		return "datetime('now')"
	default:
		return "NOW()"
	}
}

// AutoIncrement 返回自增主键定义。
func (d Dialect) AutoIncrement() string {
	switch d {
	case SQLite:
		return "INTEGER PRIMARY KEY AUTOINCREMENT"
	case MySQL:
		return "BIGINT PRIMARY KEY AUTO_INCREMENT"
	case PostgreSQL:
		return "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
	}
	return "BIGINT PRIMARY KEY AUTOINCREMENT"
}

// ColumnType 返回通用列类型映射。
func (d Dialect) ColumnType(goType string) string {
	switch goType {
	case "text":
		return "TEXT"
	case "blob":
		return "BLOB"
	case "integer":
		return "BIGINT"
	case "real":
		return "DOUBLE PRECISION"
	case "boolean":
		switch d {
		case PostgreSQL:
			return "BOOLEAN"
		default:
			return "INTEGER"
		}
	default:
		return "TEXT"
	}
}

// BoolLiteral 返回布尔值字面量。
func (d Dialect) BoolLiteral(v bool) int {
	if v {
		return 1
	}
	return 0
}
