package dialect

import (
	"strconv"
	"strings"
)

// 本文件提供结构化的建表 DSL。存在的理由是：手写三份 DDL 时，
// 「MySQL 的 TEXT 不能带 DEFAULT」「自增写法不同」「类型名不同」
// 这类差异极易在某一张表里被漏掉，交由构造器统一处理可从根上避免。

// Column 列定义。
type Column struct {
	Name string
	// Type 由 dialect 的类型方法给出（d.Text() / d.Varchar(n) / d.BigInt() …）。
	Type string
	// NotNull 追加 NOT NULL。
	NotNull bool
	// PrimaryKey 追加 PRIMARY KEY。
	PrimaryKey bool
	// Auto 追加自增修饰；仅在 PrimaryKey 时生效。
	Auto bool
	// Unique 追加 UNIQUE。
	Unique bool
	// Default 默认值 SQL 片段；空串表示无默认值。
	Default string
	// References 形如 "categories(id)"，生成列级外键。
	References string
	// OnDelete 配合 References，形如 "CASCADE" / "SET NULL"。
	OnDelete string
	// Check 形如 "status IN ('draft','published')"，生成 CHECK 约束。
	Check string
}

func (c Column) sql(d Dialect) string {
	var b strings.Builder
	b.WriteString(c.Name)
	if c.PrimaryKey && c.Auto {
		// 三库的自增主键写法差异全部收敛于此：
		//   SQLite     INTEGER PRIMARY KEY AUTOINCREMENT
		//   MySQL      BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY
		//   PostgreSQL BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
		if c.Type == "INTEGER" {
			b.WriteString(" INTEGER PRIMARY KEY AUTOINCREMENT")
		} else {
			b.WriteString(" ")
			b.WriteString(c.Type)
			b.WriteString(" NOT NULL")
			switch d {
			case PostgreSQL:
				b.WriteString(" GENERATED BY DEFAULT AS IDENTITY")
			default:
				b.WriteString(" AUTO_INCREMENT")
			}
			b.WriteString(" PRIMARY KEY")
		}
	} else {
		b.WriteByte(' ')
		b.WriteString(c.Type)
		if c.NotNull {
			b.WriteString(" NOT NULL")
		}
		if c.PrimaryKey {
			b.WriteString(" PRIMARY KEY")
		}
	}
	if c.Unique {
		b.WriteString(" UNIQUE")
	}
	if c.Default != "" {
		b.WriteString(" DEFAULT ")
		b.WriteString(c.Default)
	}
	if c.Check != "" {
		b.WriteString(" CHECK (" + c.Check + ")")
	}
	if c.References != "" {
		b.WriteString(" REFERENCES " + c.References)
		if c.OnDelete != "" {
			b.WriteString(" ON DELETE " + c.OnDelete)
		}
	}
	return b.String()
}

// Index 索引定义。
type Index struct {
	Name    string
	Columns []string
	Unique  bool
}

func (i Index) sql(d Dialect, table string) string {
	kind := "INDEX"
	if i.Unique {
		kind = "UNIQUE INDEX"
	}
	cols := make([]string, 0, len(i.Columns))
	for _, c := range i.Columns {
		cols = append(cols, d.Quote(c))
	}
	// MySQL 不支持 CREATE INDEX IF NOT EXISTS，需先查存在性再建，
	// 故此处不加 IF NOT EXISTS，由调用方（db.Migrate）负责幂等。
	ifExists := ""
	if d != MySQL {
		ifExists = "IF NOT EXISTS "
	}
	return "CREATE " + kind + " " + ifExists + d.Quote(i.Name) +
		" ON " + d.Quote(table) + " (" + strings.Join(cols, ", ") + ")"
}

// Table 表定义。
type Table struct {
	Name    string
	Columns []Column
	Indexes []Index
}

// SQL 返回该表的 CREATE TABLE 语句。
func (t Table) SQL(d Dialect) string {
	cols := make([]string, 0, len(t.Columns))
	for _, c := range t.Columns {
		cols = append(cols, c.sql(d))
	}
	ddl := "CREATE TABLE IF NOT EXISTS " + d.Quote(t.Name) +
		" (" + strings.Join(cols, ", ") + ")"
	if d == MySQL {
		// MySQL 不支持 IF NOT EXISTS 与 CHECK 同表共存的问题，
		// 但需要显式指定引擎以保证 utf8mb4 与外键生效
		ddl += " ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci"
	}
	return ddl
}

// IndexSQL 返回该表全部索引的建表语句。
func (t Table) IndexSQL(d Dialect) []string {
	out := make([]string, 0, len(t.Indexes))
	for _, i := range t.Indexes {
		out = append(out, i.sql(d, t.Name))
	}
	return out
}

// Schema 是一组表的集合，最终展开为有序的 DDL 语句列表。
type Schema struct {
	Tables []Table
}

// Statements 展开为全部 DDL 语句（建表 + 索引），顺序稳定。
func (s Schema) Statements(d Dialect) []string {
	out := make([]string, 0, len(s.Tables)*2)
	for _, t := range s.Tables {
		out = append(out, t.SQL(d))
		out = append(out, t.IndexSQL(d)...)
	}
	return out
}

// ---------- 列构造快捷方法 ----------

// ID 返回自增主键列。
//
// 注意 SQLite 的硬性要求：只有 INTEGER PRIMARY KEY 才能 AUTOINCREMENT，
// 因此 SQLite 下必须用 INTEGER 而非 BIGINT，故此处按方言取值。
func ID(d Dialect, name string) Column {
	if d == SQLite {
		return Column{Name: name, Type: "INTEGER", PrimaryKey: true, Auto: true}
	}
	return Column{Name: name, Type: d.BigInt(), PrimaryKey: true, Auto: true}
}

// TextCol 返回无界文本列（MySQL 下不带默认值）。
func TextCol(d Dialect, name string) Column {
	return Column{Name: name, Type: d.Text()}
}

// VarcharCol 返回定长文本列，默认非空且默认空串。
func VarcharCol(d Dialect, name string, max int) Column {
	return Column{Name: name, Type: d.Varchar(max), NotNull: true, Default: "''"}
}

// IntCol 返回整数列，默认非空且默认 0。
func IntCol(d Dialect, name string) Column {
	return Column{Name: name, Type: d.BigInt(), NotNull: true, Default: "0"}
}

// BoolCol 返回布尔列，默认 false。
func BoolCol(d Dialect, name string) Column {
	return Column{Name: name, Type: d.Bool(), NotNull: true, Default: d.BoolLiteral(false)}
}

// TSCol 返回时间戳列，默认取当前时间。
func TSCol(d Dialect, name string) Column {
	return Column{Name: name, Type: d.Timestamp(), NotNull: true, Default: "(" + d.NowLiteral() + ")"}
}

// NullableTSCol 返回可空时间戳列。
func NullableTSCol(d Dialect, name string) Column {
	return Column{Name: name, Type: d.Timestamp()}
}

// EnumCol 返回带 CHECK 约束的枚举列。
func EnumCol(d Dialect, name, def string, allowed ...string) Column {
	quoted := make([]string, 0, len(allowed))
	for _, a := range allowed {
		quoted = append(quoted, "'"+a+"'")
	}
	return Column{
		Name:    name,
		Type:    d.Varchar(24),
		NotNull: true,
		Default: "'" + def + "'",
		Check:   name + " IN (" + strings.Join(quoted, ",") + ")",
	}
}

// FKCol 返回指向其他表的外键列。
func FKCol(d Dialect, name, refTable, refCol, onDelete string) Column {
	return Column{
		Name:       name,
		Type:       d.BigInt(),
		References: refTable + "(" + refCol + ")",
		OnDelete:   onDelete,
	}
}

// QuoteStr 返回单引号包裹的字符串字面量（用于默认值与 CHECK）。
func QuoteStr(v string) string { return "'" + strings.ReplaceAll(v, "'", "''") + "'" }

// IntLit 返回整数字面量。
func IntLit(n int) string { return strconv.Itoa(n) }
